name: Build artifacts

on:
  push:
    #tags: 'v*'
    branch: 0-build

jobs:
  engine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev emscripten
      - name: Build & run tests
        run: |
          mkdir build
          cd build
          cmake ..
          make wasm-release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true   # TODO
          prerelease: false