name: Build artifacts

on:
  push:
    #tags: v*
    branch: 0-build

jobs:
  engine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev emscripten
      - name: Build & run tests
        run: |
          mkdir build
          cd build
          cmake ..
          make wasm-release