name: Run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  engine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev
    - name: Build & run tests
      run: |
        cmake .
        make
        make test